### ISSUE TITLE
Stuck in infinite check loop

### ISSUE THREAD

**Issue by jaakobls** [Collatty/chess#10]
See gif below.

![ezgif-7-7031aa2c7fd2](https://user-images.githubusercontent.com/54504952/140926068-ab3e3c0f-8dc4-4fef-af23-887b5af4466b.gif)

**Comment by Collatty** [comment]
Aiaiai! I see that I should implement three-fold-repetition draws. Thanks!

**Comment by Collatty** [comment]
![image](https://user-images.githubusercontent.com/32391231/141264056-b1e7a221-2540-4948-aa3a-aa966d305122.png)

@jaakobls this should be solved by #13. When a threefold repetition occurs (or the fifty-move rule) the "claim draw" button becomes clickable and ends the game.

**Comment by jaakobls** [comment]
That looks very good. An alternative would be to rewrite the bot to not allow such threefold repetitions. 🫑🧸🔱⚧☃︎㉿😵‍💫

**Comment by Collatty** [comment]
I don't feel like touching that old java code tbh
