### ISSUE TITLE
Unable to move to top-left corner with Knight

### ISSUE THREAD

**Issue by aslaksm** [Collatty/chess#9]
In the following position:

![image](https://user-images.githubusercontent.com/8820347/140917905-69de6823-25dd-4c41-84eb-ec4642a3d000.png)

I am unable to move the Knight at C7 to A8. Possibly some sort of indexing issue?

**Comment by Collatty** [comment]
@aslaksm this might have something to do with it 🥴 

![image](https://user-images.githubusercontent.com/32391231/140934774-c42ed9c4-5b4a-4b01-a709-ca840e8c112f.png)
